import React from 'react'
import "./Explore.css";
import { useNavigate } from 'react-router-dom';

const Explore = () => {
  const navigate = useNavigate();

  return (
    <div>
      <h1>Explore</h1>
      <p>Ask questions related to travelling. ChatGPT will answer. All responses are AI-generated. Example prompt and response generated by ChatGPT.</p>
      <input type='text' value="What kind of food is available in the Mystical Highlands?"></input>
      <div>
        🍽️ Highland Cuisine: A Taste of the Mystical Region<br/>
        <br/>
        The Mystical Highlands offer a mix of hearty, rustic dishes and fresh, locally sourced ingredients. Here are some must-try foods:<br/>
        <br/>
        🥩 Braised Venison Stew – A slow-cooked dish featuring tender venison, root vegetables, and a rich, herb-infused broth.<br/>
        🥔 Herb-Crusted Tattie Cakes – A crispy, savory potato dish served with smoked cheese.<br/>
        🐟 Stone-Grilled Highland Trout – Freshly caught from Mirror Lake, cooked over an open flame.<br/>
        🥖 Elderwood Bread & Forest Honey – A local specialty, often paired with berry preserves.<br/>
        🥃 Dark Oak Whiskey – A signature drink of the region, aged in mist-covered cellars for a bold, smoky flavor.<br/>
        <br/>
        Would you like recommendations on where to try these dishes during your adventure? 🍷<br/>
        <input type='text'></input>
      </div>
      <button onClick={() => navigate('/plantrip')}>What's the plan?</button>
    </div>
  )
}

export default Explore;