import './GenerateItinerary.css';


const GenerateItinerary = () => {
    return(
        <div class="page">
            <h1>Mystical Highlands Adventure: A 5-Day Journey Through Nature & Legends</h1>
            <div id="itinerary">
                Day 1: Arrival & Enchantment Begins<br/>
                📍 Arrival at Highland Lodge – Check into a cozy, mist-covered lodge nestled in the hills.<br/>
                🥘 Dinner at The Hollow Tavern – Enjoy a rustic meal by candlelight, featuring hearty local cuisine.<br/>
                🌌 Evening Walk to Starlit Ridge – A guided walk to a scenic viewpoint for stargazing.<br/>
                <br/>
                Day 2: Ancient Castles & Hidden Waterfalls<br/>
                🏰 Explore Shadowmere Castle – A legendary castle rumored to be haunted.<br/>
                🚶 Hike to Whispering Falls – A scenic 2-hour trek to a secluded waterfall.<br/>
                🍷 Dinner at The Raven’s Roost – A medieval-themed restaurant serving authentic Highland fare.<br/>
                <br/>
                Day 3: Mystical Lakes & Forgotten Caves<br/>
                🚤 Boat Tour on Mirror Lake – A guided sunrise boat ride on a glassy, reflective lake.<br/>
                🕵️ Explore the Echoing Caves – A cavern system filled with glowing moss and ancient carvings.<br/>
                🔥 Campfire Tales & Folk Music – End the night with live storytelling around a crackling fire.<br/>
                <br/>
                Day 4: Adventure & Adrenaline<br/>
                🏹 Archery & Falconry Experience – Train with skilled falconers and try your hand at traditional archery.<br/>
                🧗 Rock Climbing on Dragon’s Peak – A guided climb with breathtaking views.<br/>
                🌿 Relax at Mistwood Spa – Wind down with a herbal bath and massage.<br/>
                <br/>
                Day 5: Farewell & Final Legends<br/>
                🍵 Breakfast at The Hidden Hearth – A quiet café with fresh-baked pastries.<br/>
                📖 Visit the Lost Library of Eldoria – A hidden bookstore with rare manuscripts.<br/>
                ✈️ Depart with Memories of the Highlands
            </div>
            <p class="disclaimer">The itinerary is AI-generated. It was generated by ChatGPT.</p>
            <div id="buttons">
                <button>Modify</button>
                <button>Regenerate</button>
                <button>Save</button>
            </div>
        </div>
    )
}
export default GenerateItinerary;